# Promptext-Notes Configuration
# Controls what files are included when generating AI-powered release notes

# Files/patterns to exclude from changelog generation context
exclude:
  - "*.md"                    # Documentation files
  - ".github/**"              # CI/CD workflows
  - ".gitignore"              # Git config
  - ".dockerignore"           # Docker config
  - "go.sum"                  # Go dependency checksums
  - "*.test"                  # Test binaries
  - "coverage.out"            # Coverage reports
  - "archive/**"              # Archived code
  - "certs/**"                # Certificates
  - ".DS_Store"               # macOS files
  - "config.yaml*"            # Config examples (documented elsewhere)

# Files/patterns to include (overrides exclude)
include:
  - "go.mod"                  # Dependency changes
  - "cmd/**/*.go"             # Application entry points
  - "internal/**/*.go"        # Core Go code
  - "templates/**/*.html"     # UI templates
  - "static/**/*.css"         # Stylesheets
  - "static/**/*.js"          # JavaScript
  - "Dockerfile"              # Container config
  - "docker-compose.yml"      # Deployment config

# Custom prompts for release note generation
prompts:
  discovery: |
    You are analyzing changes for a Duo authentication testing toolkit written in Go.
    Focus on:
    - New authentication flows or types
    - UI/UX improvements
    - Security enhancements
    - Configuration changes
    - Docker/deployment updates

    Categorize changes as:
    - Added: New features
    - Changed: Modifications to existing features
    - Fixed: Bug fixes
    - Security: Security improvements
    - Deprecated: Features marked for removal

    The audience is Customer Success Engineers and technical users testing Duo integrations.

  refinement: |
    Polish the release notes to be clear, concise, and valuable for users.
    Use Keep a Changelog format.
    Focus on user-facing changes and their benefits.
    Be specific about what changed and why it matters.
